---
language: ruby
sudo: false
cache: bundler
bundler_args: --without local_development
script:
  - bundle exec rake spec
  - bundle exec rake lint:style
  - bundle exec rake lint:maintainability
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - rbx-2
  - ruby-head
matrix:
  include:
    - rvm: jruby
      env: JRUBY_OPTS='--2.0 --server -Xcompile.invokedynamic=false'
    - rvm: jruby-head
      env: JRUBY_OPTS='--server -Xcompile.invokedynamic=false'
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: jruby-head
    - rvm: ruby-head
...
